Update build-ios-release-pullrequest.yml

diff --git a/.github/workflows/build-ios-release-pullrequest.yml b/.github/workflows/build-ios-release-pullrequest.yml
--- a/.github/workflows/build-ios-release-pullrequest.yml
+++ b/.github/workflows/build-ios-release-pullrequest.yml
@@ -168,13 +168,13 @@ jobs:
     steps:
       - name: Checkout Project
         uses: actions/checkout@v4
-  
+
       - name: Set Up Ruby
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: 3.1.6
           bundler-cache: true
-  
+
       - name: Cache Ruby Gems
         uses: actions/cache@v4
         with:
@@ -182,24 +182,38 @@ jobs:
           key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
           restore-keys: |
             ${{ runner.os }}-gems-
-  
+
       - name: Install Dependencies with Bundler
         run: |
           bundle config path vendor/bundle
           bundle install --jobs 4 --retry 3 --quiet
-  
+
       - name: Download IPA from Artifact
         uses: actions/download-artifact@v4
         with:
           name: BlueWallet_${{ needs.build.outputs.project_version }}_${{ needs.build.outputs.new_build_number }}.ipa
-          path: ./
-  
-      - name: Set IPA Path Environment Variable
+          path: ./ # Download the IPA file to the current working directory
+
+      - name: Verify IPA File Download
         run: |
-          echo "IPA_OUTPUT_PATH=./BlueWallet_${{ needs.build.outputs.project_version }}_${{ needs.build.outputs.new_build_number }}.ipa" >> $GITHUB_ENV
-  
+          echo "Current directory:"
+          pwd
+          echo "Files in current directory:"
+          ls -la ./
+      
+      - name: Set IPA Path Environment Variable
+        run: echo "IPA_OUTPUT_PATH=$(pwd)/BlueWallet_${{ needs.build.outputs.project_version }}_${{ needs.build.outputs.new_build_number }}.ipa" >> $GITHUB_ENV
+
+      - name: Verify IPA Path Before Upload
+        run: |
+          if [ ! -f "$IPA_OUTPUT_PATH" ]; then
+            echo "IPA file not found at path: $IPA_OUTPUT_PATH"
+            exit 1
+          fi
+
       - name: Upload to TestFlight
         run: |
+          ls -la $IPA_OUTPUT_PATH
           bundle exec fastlane ios upload_to_testflight_lane
         env:
           MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
@@ -208,8 +222,8 @@ jobs:
           ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
           ITC_TEAM_NAME: ${{ secrets.ITC_TEAM_NAME }}
           KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-          IPA_OUTPUT_PATH: ${{ env.IPA_OUTPUT_PATH }}  # Using the environment variable set in the previous step
-  
+          IPA_OUTPUT_PATH: ${{ env.IPA_OUTPUT_PATH }}
+
       - name: Post PR Comment
         if: success() && github.event_name == 'pull_request'
         uses: actions/github-script@v6
